---
title: "Mini Project 3"
author: "Angelica Estrada & Natalia Kreciglowa"
date: "11/17/2017"
output: html_document
---
 

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#install.packages("mdsr")
library(mdsr)
library(lubridate) # for converting columns to `date` types
db <- dbConnect_scidb(dbname = "imdb")
class(db)
library(DBI)
rename <- dplyr::rename
```

<!-- ***SQL QUERY*** -->

```{r include=FALSE}
# Get the Genre of Every Movie:
genre <- db %>%
  dbGetQuery("SELECT movie_id, info_type_id, info, id 
              FROM movie_info
              WHERE info_type_id = 3;")
# save(genre, file = "genre.Rda")
```
 

```{r include=FALSE}
# Get the Release Date of Every Movie:
release <- db %>%
  dbGetQuery("SELECT movie_id, info_type_id, info, id 
              FROM movie_info
              WHERE info_type_id = 16;")
# save(release, file = "release.Rda")
```


```{r include=FALSE}
# Get the Title of Every Movie:
title <- db %>%
  dbGetQuery("SELECT id, title 
             FROM title;")
# save(title, file = "title.Rda")
```

<!-- ***DATA CLEANING IN R*** -->

```{r include=FALSE}
# Rename Id in Title:
title <- title %>%
  rename( movie_id = id )
```


```{r include=FALSE}
# Left join release date to title:
release <- release %>%
  left_join( title, by = "movie_id")
```

```{r include=FALSE}
# test duplication deletion:
library(dplyr)
datetitle <- distinct(release, title, .keep_all = TRUE)
#length(unique(duptitle$title))
#length(unique(title$title))
#length(unique(release$title))
#length(unique(datetitle$movie_id))
```

```{r include=FALSE}
# Count the number of genres per movie_id:
genrecount <- genre %>%
  group_by( movie_id ) %>%
  summarise( genrecount = n() ) 
# length(unique(genrecount$movie_id))
# length(unique(genre$movie_id))
```

```{r include=FALSE}
# Join Date, Title and Genre Count information:
movieinfo <- datetitle %>%
  inner_join(genrecount, by = "movie_id" )
```

<!-- Create `year` column by extracting year from existing data frame -->

```{r include=FALSE}
# Split `info` column into `country` and `date` 
movieinfo <- movieinfo %>%
  separate(col = info, 
           into = c("country", "date"), 
           sep = "\\:")

# Formatting of values in `date` column (1 of 3 types):
# 1. day month year
# 2. month year
# 3. year
```
    
```{r include=FALSE}
# Uses lubridate package

# Create new date column in date format
movieinfo <- movieinfo %>%
  mutate(dates = dmy(date))

# Values in the "day month year" were the only rows that were correctly parsed
# Need to fix the remaining 231521 rows that failed to parse
```

<!-- Resolving year issue for values in "day month year" and "year" format -->

```{r include=FALSE}
# Convert `date` to numeric and save as a vector called `year`
# as.numeric() will:
#   1. Extract the "year" from `date` values in the "day month year" format and convert the character to numeric
#   2. Convert values in the "year" format to numeric
# Values in the "month year" format will be coded as NA but this will be fixed later

yr <- as.numeric(movieinfo$date)
```
    
```{r include=FALSE}
### Code below just ensures that `yr` contains only years 
### (skip this chunk but don't delete)

# #count number of `NA`'s in `date`
# sum(is.na(yr)) # 712118 NA's
# 
# #count number of years not including NA
# length(yr)-sum(is.na(yr)) #147324 elements
#  
# # Create vector only containing year and no NA
# yronly <- na.omit(yr) 
# length(yronly) #147324 elements
# 
# # Check that all values in `yronly` are greater than 1800 (to make sure there are no days)
# length(yronly > 1800) #147324 elements (matches!)
```
    

```{r include=FALSE}
# Add `yr` column to `movieinfo`
movieinfo <- movieinfo %>%
  mutate(yr = yr)

# Split `date` column to `day`, `month`, `year` and while keeping `date` column

d <- movieinfo$date

movieinfo <- movieinfo %>%
  separate(col = date,
           into = c("day", "month", "year"),
           sep = "\\ ")

movieinfo <- movieinfo %>%
  mutate(date=d)

# Here we see that some `day` values are listed as a month, and some `month` values are listed as a year. This will be resolved in the code below.
```

```{r include=FALSE}
# Convert `day` and `year` columns to numeric
# Any `day` values containing a month or string will be coerced to NA
movieinfo <- movieinfo %>%
  mutate(day = as.numeric(day),
         year = as.numeric(year))

# Combine `yr` and `year` columns into `year` column
movieinfo <- movieinfo %>%
  mutate(year = ifelse(is.na(year) == TRUE, yr, year))
```
    
<!-- Resolving year issue for values in "month year" format -->
 
```{r include=FALSE}
# Split `movieinfo` into 2 dataframes based on (non)missing years

# First split: all movies with year
yr <- movieinfo %>%
  filter(!is.na(year))

# Second split: all movies without year (year = NA)
missing_yr <- movieinfo %>%
  filter(is.na(year))

# Check: Do the number of rows in `yr` and `missing_yr` add up to 859442? YES!
 nrow(yr) + nrow(missing_yr)
```
    
```{r include=FALSE}
# Within `missing_yr`, we see that `month` column only contains the year and the `year` column has all NA's

# Replace the NA's in `year` column by values in `month` column  
missing_yr <- missing_yr %>%
  mutate(year = month)
```
    
```{r include=FALSE}
# Combine both `yr` and `missing_yr` dataframes into a single dataframe called `movies_df` 
movies_df <- rbind(yr, missing_yr)

# Double check for any missing years? 0 missing years, we're good to go!
sum(is.na(movies_df$year)) 
```
   
<!-- ***CLEAN AND FINAL DATAFRAME TO USE: `movies`*** -->     
     
```{r include=FALSE}
# Select relevant columns from `movies` and save as a clean & final dataframe: `movies` 
# Only considering `year`

movies <- movies_df %>%
  select(movie_id, title, year, genrecount, country)

```
    
<!-- ***PLOTS*** -->
 


```{r}
# Create Plot.ly:
library(plotly)
usmovieplot <- plot_ly(data = usamovies, x = ~year, y = ~genrecount,
        marker = list(size = 10,
                       color = 'rgba(255, 182, 193, .9)',
                       line = list(color = 'rgba(152, 0, 0, .8)',
                                   width = 2))) %>%
  layout(title = 'Genre Count per Year',
         yaxis = list(zeroline = FALSE),
         xaxis = list(zeroline = FALSE))
usmovieplot
```



```{r}
usmoviedateplot <- plot_ly(data = usamoviesdates, x = ~year, y = ~genrecount,
        marker = list(size = 10,
                       color = 'skyblue',
                       line = list(color = 'lightgrey',
                                   width = 2))) %>%
  layout(title = 'Genre Count per Year',
         yaxis = list(zeroline = FALSE),
         xaxis = list(zeroline = FALSE))
usmoviedateplot
```

```{r}
p <- ggplot(usmoviedateplot, aes(year, genrecount)) +
  geom_point() + 
  geom_jitter(width = 1, height = 1) + 
  ggtitle("Genre Count per Movie")

p <- ggplotly(p)

p
```


```{r}
ggplot(usmoviedateplot, aes(year, genrecount)) +
  geom_point() + 
  geom_jitter(width = 1, height = 1) + 
  ggtitle("Genre Count per Movie")
```

```{r}
# Create data for US plots only:
usamovies <- movies %>%
  filter( country == "USA")
usamovies$year <- as.numeric(as.character(usamovies$year))
```

```{r}
# Clean data for observation years:
usamoviesdates <- usamovies %>%
  filter( year >= 1937 ) %>%
  filter( year <= 1957 )
```

```{r}
# Clean Data for a genre % of total movies per year:
genresplit <- usamoviesdates %>%
  group_by( year ) %>%
  summarize( totalmovies = n()) 
```

```{r}
# Clean Data for each genre count per year:
genresplit1 <- usamoviesdates %>% 
  filter( genrecount == 1 ) %>%
  group_by( year ) %>%
  summarize( totalgenre1 = n()) 
genresplit2 <- usamoviesdates %>% 
  filter( genrecount == 2 ) %>%
  group_by( year ) %>%
  summarize( totalgenre2 = n()) 
genresplit3 <- usamoviesdates %>% 
  filter( genrecount == 3 ) %>%
  group_by( year ) %>%
  summarize( totalgenre3 = n()) 
genresplit4 <- usamoviesdates %>% 
  filter( genrecount == 4 ) %>%
  group_by( year ) %>%
  summarize( totalgenre4 = n()) 
genresplit5 <- usamoviesdates %>% 
  filter( genrecount == 5 ) %>%
  group_by( year ) %>%
  summarize( totalgenre5 = n()) 
genresplit6 <- usamoviesdates %>% 
  filter( genrecount == 6 ) %>%
  group_by( year ) %>%
  summarize( totalgenre6 = n()) 
genresplit7 <- usamoviesdates %>% 
  filter( genrecount == 7 ) %>%
  group_by( year ) %>%
  summarize( totalgenre7 = n()) 
genresplit8 <- usamoviesdates %>% 
  filter( genrecount == 8 ) %>%
  group_by( year ) %>%
  summarize( totalgenre8 = n()) 
genresplit9 <- usamoviesdates %>% 
  filter( genrecount == 9 ) %>%
  group_by( year ) %>%
  summarize( totalgenre9 = n()) 
```

```{r}
# Join the different genre count data frames:
genresplit <- genresplit %>%
  full_join( genresplit1, by= "year")
genresplit <- genresplit %>%
  full_join( genresplit2, by= "year") 
genresplit <- genresplit %>%
  full_join( genresplit3, by= "year") 
genresplit <- genresplit %>%
  full_join( genresplit4, by= "year") 
genresplit <- genresplit %>%
  full_join( genresplit5, by= "year") 
genresplit <- genresplit %>%
  full_join( genresplit6, by= "year") 
genresplit <- genresplit %>%
  full_join( genresplit7, by= "year") 
genresplit <- genresplit %>%
  full_join( genresplit8, by= "year") 
genresplit <- genresplit %>%
  full_join( genresplit9, by= "year") 
genresplit[is.na(genresplit)] <- 0
```


```{r}
# Mutate for proportion:
genresplit <- genresplit %>%
  mutate( Prop1Genre = totalgenre1 / totalmovies) %>%
  mutate( Prop2Genre = totalgenre2 / totalmovies) %>%
  mutate( Prop3Genre = totalgenre3 / totalmovies) %>%
  mutate( Prop4Genre = totalgenre4 / totalmovies) %>%
  mutate( Prop5Genre = totalgenre5 / totalmovies) %>%
  mutate( Prop6Genre = totalgenre6 / totalmovies) %>%
  mutate( Prop7Genre = totalgenre7 / totalmovies) %>%
  mutate( Prop8Genre = totalgenre8 / totalmovies) %>%
  mutate( Prop9Genre = totalgenre9 / totalmovies) 
```

```{r}
# Create clean data frame:
library(reshape2)
genresplitclean <- genresplit %>%
  select(year, Prop1Genre, Prop2Genre, Prop3Genre, Prop4Genre, Prop5Genre, Prop6Genre, Prop7Genre, Prop8Genre, Prop9Genre) %>%
  rename( Year = year )
mgenresplitclean <- melt( genresplitclean, id = c("Year"))
mgenresplitclean <- mgenresplitclean %>%
  rename(GenreCount= variable) %>%
  rename(Percent = value)
ggplot(mgenresplitclean , aes( x= Year, Percent, fill = GenreCount)) +
  geom_bar(position = "fill", stat = "identity") 
```

<!-- RESOURCES

Splitting a single column into multiple columns
# https://stackoverflow.com/questions/7069076/split-column-at-delimiter-in-data-frame  (uses tidyr package)

Convert to dates
http://blog.yhat.com/static/pdf/R_date_cheat_sheet.pdf
https://rpubs.com/davoodastaraky/lubridate
https://www.statmethods.net/input/dates.html

-->

